"""
Chatbot API router for the Physical AI & Humanoid Robotics textbook platform.
"""
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import Optional

from ..middleware.auth import get_current_user
from ..models import User, ChatSession, ChatMessage
from ..database import get_db
from ..services.rag_service import RAGService

router = APIRouter()

@router.post("/session")
async def create_chat_session(
    module_id: Optional[str] = None,
    chapter_id: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create a new chat session for a user.
    """
    # Create a new chat session in the database
    chat_session = ChatSession(
        user_id=current_user.id,
        module_id=module_id,
        chapter_id=chapter_id
    )

    db.add(chat_session)
    db.commit()
    db.refresh(chat_session)

    return {
        "session_id": chat_session.id,
        "created_at": chat_session.created_at.isoformat()
    }


@router.post("/query")
async def submit_query(
    session_id: str,
    query: str,
    context: Optional[dict] = None,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Submit a question to the chatbot and receive a response.
    """
    # Verify that the session belongs to the current user
    session = db.query(ChatSession).filter(
        ChatSession.id == session_id,
        ChatSession.user_id == current_user.id
    ).first()

    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found or does not belong to user"
        )

    # Add the user's message to the database
    user_message = ChatMessage(
        session_id=session_id,
        role="user",
        content=query
    )
    db.add(user_message)
    db.commit()

    # Use RAG service to generate response
    rag_service = RAGService()
    response = await rag_service.get_response(query, current_user.id, session_id)

    # Add the assistant's response to the database
    assistant_message = ChatMessage(
        session_id=session_id,
        role="assistant",
        content=response
    )
    db.add(assistant_message)
    db.commit()

    return {
        "response": response,
        "sources": ["source_1", "source_2"],  # In a real implementation, these would come from the RAG service
        "followup_questions": ["Follow-up question 1?", "Follow-up question 2?"]  # In a real implementation, these would be generated by the LLM
    }


@router.get("/session/{session_id}")
async def get_session_history(
    session_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Retrieve the history of messages in a chat session.
    """
    # Verify that the session belongs to the current user
    session = db.query(ChatSession).filter(
        ChatSession.id == session_id,
        ChatSession.user_id == current_user.id
    ).first()

    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found or does not belong to user"
        )

    # Get all messages for this session
    messages = db.query(ChatMessage).filter(
        ChatMessage.session_id == session_id
    ).order_by(ChatMessage.timestamp).all()

    formatted_messages = []
    for msg in messages:
        formatted_messages.append({
            "id": msg.id,
            "role": msg.role,
            "content": msg.content,
            "timestamp": msg.timestamp.isoformat()
        })

    return {
        "session_id": session_id,
        "messages": formatted_messages
    }